[project]
name = 'Environmental-Impact-Monitoring'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance-threshold]
path = 'contracts/compliance-threshold.clar'
clarity_version = 2
epoch = 2.5

[contracts.facility-verification]
path = 'contracts/facility-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.reporting]
path = 'contracts/reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-data]
path = 'contracts/sensor-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
